version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build client application Docker image
          command: |
            docker build -t bennycheng/client-test -f ./client/Dockerfile.dev ./client
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Test client application Docker image
          command: |
            docker run bennycheng/client-test npm run test:ci
      - run:
          name: Build application Docker image
          command: |
            docker build -t bennycheng/multi-client ./client
            docker build -t bennycheng/multi-nginx ./nginx
            docker build -t bennycheng/multi-server ./server
            docker build -t bennycheng/multi-worker ./worker

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
        requires
          - build
