version: 2.1
executors:
  docker-executor:
    docker:
      -image: cimg/base:2021.04
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.14
          docker_layer_caching: true
      - run:
          name: Build client application Docker image
          command: |
            docker build -t bennycheng/client-test -f ./client/Dockerfile.dev ./client
  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.14
          docker_layer_caching: true
      - run:
          name: Test client application Docker image
          command: |
            docker run bennycheng/client-test npm run test:ci
      - run:
          name: Build application Docker image
          command: |
            docker build -t bennycheng/multi-client ./client
            docker build -t bennycheng/multi-nginx ./nginx
            docker build -t bennycheng/multi-server ./server
            docker build -t bennycheng/multi-worker ./worker

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
