version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
        version: 19.03.13
        docker_layer_caching: true
      - run:
          name: Build client application Docker image
          command: |
            docker build -t bennycheng/client-test -f ./client/Dockerfile.dev ./client
      - run:
          name: Test client application Docker image
          command: |
            docker run bennycheng/client-test npm run test:ci -- --coverage
      - run:
          name: Build application Docker image
          command: |
            docker build -t bennycheng/multi-client -f ./client
            docker build -t bennycheng/multi-nginx -f ./nginx
            docker build -t bennycheng/multi-server -f ./server
            docker build -t bennycheng/multi-worker -f ./worker

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
